on:
  push:
    branches:
      - master
name: 🚀 Deploy Production
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔨 Build Project
        run: |
          yarn install
          yarn run lint:fix
          yarn run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: "./dist/"
          remote-dir: "/"
